// port-lint: source src/lib.rs

/**
 * **Typed distributed plugin registration.**
 *
 * This package provides a way to set up a plugin registry into which plugins
 * can be registered from any source file linked into your application. There
 * does not need to be a central list of all the plugins.
 *
 * # Examples
 *
 * Suppose we are writing a command line flags library and want to allow any
 * source file in the application to register command line flags that are
 * relevant to it.
 *
 * This is the flag registration style used by gflags and is better suited
 * for large scale development than maintaining a single central list of flags,
 * as the central list would become an endless source of merge conflicts in an
 * application developed simultaneously by thousands of developers.
 *
 * ## Instantiating the plugin registry
 *
 * Let's use a `class Flag` as the plugin type, which will contain the short
 * name of the flag like `-v`, the full name like `--verbose`, and maybe other
 * information like argument type and help text. We instantiate a plugin
 * registry with an invocation of [collect].
 *
 * ```
 * class Flag(
 *     val short: Char,
 *     val name: String,
 *     /* ... */
 * )
 *
 * collect(Flag::class)
 * ```
 *
 * This [collect] call must be in the same module that defines the plugin type.
 * Place it outside of any function body — for example, in a top-level `init`
 * block backed by a property — so that it runs once when the module loads.
 *
 * ## Registering plugins
 *
 * Now any module with access to the `Flag` type can register flags as a
 * plugin. Plugins can be registered by the same module that declares the
 * plugin type, or by any downstream module.
 *
 * ```
 * submit(Flag(short = 'v', name = "verbose"))
 * ```
 *
 * Place [submit] invocations outside of any function body. All [submit]
 * invocations across all source files linked into your application all take
 * effect at module load time. A [submit] invocation is not a statement that
 * needs to be called from `main` in order to execute.
 *
 * ## Iterating over plugins
 *
 * The function [iter] returns an iterator with element type `T` that iterates
 * over all plugins registered of type `T`.
 *
 * ```
 * for (flag in iter<Flag>()) {
 *     println("-${flag.short}, --${flag.name}")
 * }
 * ```
 *
 * There is no guarantee about the order that plugins of the same type are
 * visited by the iterator. They may be visited in any order.
 *
 * ## WebAssembly and constructors
 *
 * `inventory` supports all WebAssembly targets, including
 * `wasm*-unknown-unknown`. However, in unusual circumstances, ensuring that
 * constructors run may require some extra effort. The Wasm linker will
 * synthesize a function that calls all constructors when invoked; this
 * function will *not* be exported from the module unless you do so
 * explicitly. Depending on the result of a heuristic, the linker may or may
 * not insert a call to this function from the beginning of every function
 * that your module exports. Specifically, it regards a module as having
 * "command-style linkage" if:
 *
 * * it is not relocatable;
 * * it is not a position-independent executable;
 * * and it does not call the constructor entry, directly or indirectly, from
 *   any exported function.
 *
 * The linker expects that the embedder will call into a command-style module
 * only once per instantiation. Violation of this expectation can result in
 * the constructor entry being called multiple times. This is dangerous in
 * general, but safe and mostly harmless in the case of constructors generated
 * by `inventory`, which are idempotent.
 *
 * If you are building a module which relies on constructors and may be called
 * into multiple times per instance, you should ensure that the embedder calls
 * the constructor entry immediately after instantiation. Even though
 * `inventory` may work fine without this, it is still good practice, because
 * it avoids unnecessary overhead from repeated constructor invocation. It
 * also can prevent unsoundness if some of your constructors are generated by
 * other modules or other programming languages.
 */
package io.github.kotlinmania.inventory

import kotlin.concurrent.atomics.AtomicReference
import kotlin.reflect.KClass

private val registries: AtomicReference<RegistryMap> =
    AtomicReference(RegistryMap.EMPTY)

private class RegistryMap private constructor(
    private val entries: List<Pair<KClass<*>, Registry>>,
) {
    fun get(klass: KClass<*>): Registry? {
        for ((k, v) in entries) {
            if (k == klass) return v
        }
        return null
    }

    fun put(klass: KClass<*>, registry: Registry): RegistryMap {
        return RegistryMap(entries + (klass to registry))
    }

    companion object {
        val EMPTY: RegistryMap = RegistryMap(emptyList())
    }
}

@PublishedApi
internal fun registryFor(klass: KClass<*>): Registry {
    while (true) {
        val current = registries.load()
        current.get(klass)?.let { return it }
        val fresh = Registry()
        val updated = current.put(klass, fresh)
        if (registries.compareAndSet(current, updated)) {
            return fresh
        }
    }
}
