// port-lint: source src/lib.rs
package io.github.kotlinmania.inventory

import kotlin.concurrent.atomics.AtomicBoolean
import kotlin.concurrent.atomics.AtomicReference
import kotlin.reflect.KClass

/**
 * **Typed distributed plugin registration.**
 *
 * This package provides a way to set up a plugin registry into which plugins
 * can be registered from any source file linked into your application. There
 * does not need to be a central list of all the plugins.
 *
 * # Examples
 *
 * Suppose we are writing a command line flags library and want to allow any
 * source file in the application to register command line flags that are
 * relevant to it.
 *
 * This is the flag registration style used by gflags and is better suited
 * for large scale development than maintaining a single central list of flags,
 * as the central list would become an endless source of merge conflicts in an
 * application developed simultaneously by thousands of developers.
 *
 * ## Instantiating the plugin registry
 *
 * Let's use a `class Flag` as the plugin type, which will contain the short
 * name of the flag like `-v`, the full name like `--verbose`, and maybe other
 * information like argument type and help text. We instantiate a plugin
 * registry with an invocation of [collect].
 *
 * ```
 * class Flag(
 *     val short: Char,
 *     val name: String,
 *     /* ... */
 * )
 *
 * collect(Flag::class)
 * ```
 *
 * This [collect] call must be in the same module that defines the plugin type.
 * Place it outside of any function body — for example, in a top-level `init`
 * block backed by a property — so that it runs once when the module loads.
 *
 * ## Registering plugins
 *
 * Now any module with access to the `Flag` type can register flags as a
 * plugin. Plugins can be registered by the same module that declares the
 * plugin type, or by any downstream module.
 *
 * ```
 * submit(Flag(short = 'v', name = "verbose"))
 * ```
 *
 * Place [submit] invocations outside of any function body. All [submit]
 * invocations across all source files linked into your application all take
 * effect at module load time. A [submit] invocation is not a statement that
 * needs to be called from `main` in order to execute.
 *
 * ## Iterating over plugins
 *
 * The function [iter] returns an iterator with element type `T` that iterates
 * over all plugins registered of type `T`.
 *
 * ```
 * for (flag in iter<Flag>()) {
 *     println("-${flag.short}, --${flag.name}")
 * }
 * ```
 *
 * There is no guarantee about the order that plugins of the same type are
 * visited by the iterator. They may be visited in any order.
 *
 * ## WebAssembly and constructors
 *
 * `inventory` supports all WebAssembly targets, including
 * `wasm*-unknown-unknown`. However, in unusual circumstances, ensuring that
 * constructors run may require some extra effort. The Wasm linker will
 * synthesize a function that calls all constructors when invoked; this
 * function will *not* be exported from the module unless you do so
 * explicitly. Depending on the result of a heuristic, the linker may or may
 * not insert a call to this function from the beginning of every function
 * that your module exports. Specifically, it regards a module as having
 * "command-style linkage" if:
 *
 * * it is not relocatable;
 * * it is not a position-independent executable;
 * * and it does not call the constructor entry, directly or indirectly, from
 *   any exported function.
 *
 * The linker expects that the embedder will call into a command-style module
 * only once per instantiation. Violation of this expectation can result in
 * the constructor entry being called multiple times. This is dangerous in
 * general, but safe and mostly harmless in the case of constructors generated
 * by `inventory`, which are idempotent.
 *
 * If you are building a module which relies on constructors and may be called
 * into multiple times per instance, you should ensure that the embedder calls
 * the constructor entry immediately after instantiation. Even though
 * `inventory` may work fine without this, it is still good practice, because
 * it avoids unnecessary overhead from repeated constructor invocation. It
 * also can prevent unsoundness if some of your constructors are generated by
 * other modules or other programming languages.
 */

// Not public API. Used by generated code.
public class Registry @PublishedApi internal constructor() {
    @PublishedApi
    internal val head: AtomicReference<Node?> = AtomicReference(null)

    // The `value` is thread-safe, and `next` is only mutated during submit,
    // which is prior to any reads.
    internal fun submit(new: Node) {
        // The WebAssembly linker uses an unreliable heuristic to determine
        // whether a module is a "command-style" linkage, for which it will
        // insert a call to the constructor entry at the top of every exported
        // function. It expects that the embedder will call into such modules
        // only once per instantiation. If this heuristic goes wrong, we can
        // end up having our constructors invoked multiple times, which
        // without this safeguard would lead to our registry's linked list
        // becoming circular. This check is harmless on non-Wasm platforms, so
        // we apply it uniformly.
        if (new.initialized.exchange(true)) {
            return
        }

        var head = this.head.load()
        while (true) {
            new.next.store(head)
            val prev = this.head.compareAndExchange(head, new)
            if (prev === head) {
                return
            }
            head = prev
        }
    }
}

// Not public API. Used by generated code.
public class Node internal constructor(
    public val value: ErasedNode,
) {
    public val next: AtomicReference<Node?> = AtomicReference(null)
    internal val initialized: AtomicBoolean = AtomicBoolean(false)
}

// Not public API. Used by generated code.
public interface ErasedNode {
    // Requires that the underlying value's type matches the registry this
    // node will join.
    public fun submit(node: Node)
}

private class CollectNode(
    val unwrapped: Any,
    private val klass: KClass<*>,
) : ErasedNode {
    override fun submit(node: Node) {
        registryFor(klass).submit(node)
    }
}

/**
 * Marker interface for types that can be iterated by [iter].
 *
 * This interface cannot be implemented manually beyond inheriting from it.
 * The actual binding between a plugin type and its registry is established by
 * the [collect] call, which records the type as a collectable plugin type at
 * runtime.
 *
 * # Examples
 *
 * ```
 * fun <T : Any> countPlugins(klass: KClass<T>): Int = iter(klass).asSequence().count()
 * ```
 */
public interface Collect

private val registries: AtomicReference<RegistryMap> =
    AtomicReference(RegistryMap.EMPTY)

private class RegistryMap private constructor(
    private val entries: List<Pair<KClass<*>, Registry>>,
) {
    fun get(klass: KClass<*>): Registry? {
        for ((k, v) in entries) {
            if (k == klass) return v
        }
        return null
    }

    fun put(klass: KClass<*>, registry: Registry): RegistryMap {
        return RegistryMap(entries + (klass to registry))
    }

    companion object {
        val EMPTY: RegistryMap = RegistryMap(emptyList())
    }
}

@PublishedApi
internal fun registryFor(klass: KClass<*>): Registry {
    while (true) {
        val current = registries.load()
        current.get(klass)?.let { return it }
        val fresh = Registry()
        val updated = current.put(klass, fresh)
        if (registries.compareAndSet(current, updated)) {
            return fresh
        }
    }
}

/**
 * Associate a plugin registry with the specified type.
 *
 * This call must be in the same module that defines the plugin type. It does
 * not "run" anything; it simply ensures the per-type [Registry] exists. Place
 * it outside of any function body — for example, behind a top-level
 * initializer — so that it runs once when the module loads.
 *
 * # Examples
 *
 * Suppose we are writing a command line flags library and want to allow any
 * source file in the application to register command line flags that are
 * relevant to it.
 *
 * This is the flag registration style used by gflags and is better suited for
 * large scale development than maintaining a single central list of flags, as
 * the central list would become an endless source of merge conflicts.
 *
 * ```
 * class Flag(
 *     val short: Char,
 *     val name: String,
 *     /* ... */
 * )
 *
 * collect(Flag::class)
 * ```
 *
 * Refer to the package-level documentation for a complete example of
 * submitting plugins and iterating a plugin registry.
 */
public fun <T : Any> collect(klass: KClass<T>): Registry = registryFor(klass)

/**
 * Enter an element into the plugin registry corresponding to its type.
 *
 * This call may be in the same module that defines the type, or downstream in
 * any module that depends on that module.
 *
 * Place [submit] invocations outside of any function body. All [submit]
 * invocations across all source files linked into your application take
 * effect at module load time. A [submit] invocation is not a statement that
 * needs to be called from `main` in order to execute.
 *
 * # Examples
 *
 * Put [submit] invocations outside of any function body, behind a top-level
 * initializer:
 *
 * ```
 * private val registerVerbose = submit(Flag(short = 'v', name = "verbose"))
 * ```
 *
 * Do not invoke [submit] conditionally from inside a function body when you
 * want it to take effect at startup; it does not do what you want.
 *
 * Refer to the package-level documentation for a complete example of
 * instantiating and iterating a plugin registry.
 */
public inline fun <reified T : Any> submit(value: T) {
    submit(value, T::class)
}

@PublishedApi
internal fun <T : Any> submit(value: T, klass: KClass<T>) {
    val erased = CollectNode(value, klass)
    val node = Node(erased)
    erased.submit(node)
}

/**
 * An iterator over plugins registered of a given type.
 *
 * The function [iter] returns an iterator with element type `T`.
 *
 * There is no guarantee about the order that plugins of the same type are
 * visited by the iterator. They may be visited in any order.
 *
 * # Examples
 *
 * ```
 * for (flag in iter<Flag>()) {
 *     println("-${flag.short}, --${flag.name}")
 * }
 * ```
 *
 * Refer to the package-level documentation for a complete example of
 * instantiating a plugin registry and submitting plugins.
 */
public class Iter<T : Any> @PublishedApi internal constructor(
    private var node: Node?,
    @PublishedApi internal val extract: (Any) -> T,
) : Iterator<T> {

    override fun hasNext(): Boolean = node != null

    override fun next(): T {
        val current = node ?: throw NoSuchElementException()
        node = current.next.load()
        val payload = current.value
        if (payload !is CollectNode) {
            throw IllegalStateException("inventory: corrupt node")
        }
        return extract(payload.unwrapped)
    }

    /**
     * Returns an iterator that resumes from the same position. Equivalent to
     * `impl Clone for Iter<T>` upstream: the new iterator visits the same
     * remaining nodes as this one, independently.
     */
    public fun copy(): Iter<T> = Iter(node, extract)
}

/**
 * Returns an iterator over all plugins registered for the given type.
 *
 * Equivalent to the upstream value `inventory::iter::<T>` together with its
 * `IntoIterator` impl: calling this function is the same as taking that ghost
 * value and asking it for an iterator.
 */
public inline fun <reified T : Any> iter(): Iter<T> {
    val head = registryFor(T::class).head.load()
    return Iter(head) { value ->
        if (value is T) {
            value
        } else {
            throw IllegalStateException("inventory: registry contained an incompatible value")
        }
    }
}
